#!/bin/bash

BASEURL="http://www.ipdeny.com/ipblocks/data/countries"
DOWNPROG="curl -s "

usage() {
	echo "Usage: $0 -c country -t target" 1>&2;
	exit 1;
}

while getopts ":c:" o; do
    case "${o}" in
        c)
            c=${OPTARG}
            ;;
        t)
            t=${TARGET}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${c}" ] ; then
    usage
fi

CHAIN="${c}"
FILE=${c}.iptables
TARGET=${TARGET:-"DROP"}



IPS=$($DOWNPROG $BASEURL/${c}.zone)

echo "*filter" > $FILE 
echo ":${CHAIN} - [0:0]" >> $FILE 

for ip in $IPS
do
    echo "-A $CHAIN -s $ip -j $TARGET" >> $FILE 
done
echo "-A $CHAIN -j RETURN" >> $FILE
echo "COMMIT" >> $FILE

