#!/bin/bash

BASEURL="http://www.ipdeny.com/ipblocks/data/countries"

usage() {
	echo "Usage: $0 -c country" 1>&2;
	exit 1;
}

while getopts ":c:" o; do
    case "${o}" in
        c)
            c=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${c}" ] ; then
    usage
fi
