#!/bin/bash

BASEURL="http://www.ipdeny.com/ipblocks/data/countries"
DOWNPROG="curl -s "

usage() {
	echo "Usage: $0 -c country [-t target] [-n chain name] [-l]" 1>&2;
	exit 1;
}

while getopts ":c:t:n:l" o; do
    case "${o}" in
        c)
            COUNTRY=${OPTARG}
            ;;
        t)
            TARGET=${OPTARG}
            ;;
        n)
            CHAIN=${OPTARG}
            ;;
        l)
            LOAD=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${COUNTRY}" ] ; then
    usage
fi

CHAIN="${CHAIN:-$COUNTRY}"
FILE=${COUNTRY}.iptables
TARGET=${TARGET:-"DROP"}



IPS=$($DOWNPROG $BASEURL/${c}.zone)

echo "*filter" > $FILE 
echo ":${CHAIN} - [0:0]" >> $FILE 

for ip in $IPS
do
    echo "-A $CHAIN -s $ip -j $TARGET" >> $FILE 
done
echo "-A $CHAIN -j RETURN" >> $FILE
echo "COMMIT" >> $FILE

if [ -n $LOAD ]; then
	iptables-restore -n < $FILE
fi

